### PR TITLE
Client-side routing

### LINKED ISSUE #41: Investigate ways to reduce size of routes.json
Right now, it's 1 megabyte. As more destinations are added, the size of the file will increase exponentally.

### PR DESCRIPTION
**Pull request by Gjum**
fixes #41 and #46

try it out here: https://gjum.github.io/KANI/

### CODE REVIEW

**Comment by Ameliorate** [comment]
This is amazing. I think the only thing missing is when the node has `station = true` and it's the end-dest, to add `[end-dest]:exit` to the command.

**Comment by Gjum** [comment]
> station = true

Ok so that's how it works. I'll fix that today.

**Comment by Gjum** [comment]
oh before you merge, I should add some fancy discord embed box to it, hold on

**Comment by Ameliorate** [comment]
If your start-dest is a TerminalDestination (not a switch nor station), the page will refuse to generate a /dest command.
https://gjum.github.io/KANI/#its:office#icenia

**Pull request merged**
