### PR TITLE
Create j:icegen.toml

### PR DESCRIPTION
**Pull request by patrick1bauer**
Created a KANI compliant intersection on the icenia - gensokyo:taozi and gensokyo:roe - j:knot lines.

### CODE REVIEW

**Comment by Ameliorate** [comment]
Could you also modify the switches this junction is connected to to satisfy the linter?

**Comment by Ameliorate** [comment]
Also instead of station = false, you should do switch = true.

**Comment by patrick1bauer** [comment]
Changed "station = false" to "switch = true".

**Comment by Ameliorate** [comment]
The way you did the PRs is a little weird, but this all should work I think.

**Pull request merged**
